version: "3.9"
services:
  backend:
    image: openjdk:17
    container_name: backend-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/task_management
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver

    depends_on:
      - database

  frontend:
    image: node:16
    container_name: frontend-service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - ANGULAR_ENV=development
      - apiBaseUrl = 'http://localhost:8080/api'
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
