version: '3.8'

services:
  backend:
    container_name: backend-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/task_management
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - database

  frontend:
    container_name: frontend-service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - ANGULAR_ENV=production
      - apiBaseUrl=http://backend:8080/api
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: